### PR TITLE
Merge Invitae local changes used to build recent UTA

### PR DESCRIPTION
**Pull request by reece**
#229 requested to merge changes necessary for a recent UTA build. Due to configuration issues on minion, the build machine, those changes were misattributed to `biocommons` and to me. 

This PR consists of exactly the same changes at #229, with authorship reset to @safay using rebase. (Although this rewrites history, the history in question is on a fork, not on this repo.)

@safay: Please review these changes and confirm the authorship reset. If okay, I'll merge into main.

### CODE REVIEW

**Comment by reece** [comment]
@andreasprlic , @safay , @cjvillar: Take 2 on reassigning authorship.

**Review by andreasprlic — APPROVED** [review]
Travis is failing, but looks good to me otherwise.

**Comment by reece** [comment]
@safay and @cjvillar : Are you both okay with this attribution?

**Comment by cjvillar** [comment]
@reece LGTM, Thanks.

**Comment by reece** [comment]
@safay Notified by slack earlier.

image

**Pull request merged**
